### ISSUE TITLE
Common project for Bibframe2 SPARQL

### ISSUE THREAD

**Issue by dazza-codes** [NatLibFi/bib-rdf-pipeline#31]
Can we extract some SPARQL code into a generic Bibframe2 project for SPARQL?

- https://github.com/NatLibFi/bib-rdf-pipeline/tree/master/sparql

Could we do this under the umbrella of an LC and/or LD4L/LD4P github org?  If so, how would this project integrate an upstream project for SPARQL code?  How would this project manage generally useful SPARQL on Bibframe2 vs. some SPARQL that is very specific to this project?

**Comment by osma** [comment]
Can you elaborate on what goals such a project would have?

If there were generic SPARQL queries available, it would be no problem for me to use them from this project. I'm already stringing together lots of tools, moving one or a few components (the SPARQL queries) into another project would just be adding another dependency. But of course, the queries would have to be specified in such a way that I could reasonably rely on them not breaking my conversion.

**Comment by dazza-codes** [comment]
Good points.  Perhaps it would be OK to copy SPARQL from this project into a generic collection of SPARQL in https://github.com/ld4l-labs/bibframe2-sparql ?

**Comment by osma** [comment]
@darrenleeweber Of course. Everything in this repo is CC0 licensed.

I'm not sure whether "collection of SPARQL queries for BIBFRAME2" is a good focus for a repository, though. I think there should be a more specific goal than just an intersection of technologies.

**Comment by osma** [comment]
Closing this issue, as it doesn't propose any changes to this repository.
