### ISSUE TITLE
If bf:itemOf present an "electronic instance" is created

### ISSUE THREAD

**Issue by HorvathAdam** [NatLibFi/bib-rdf-pipeline#92]
If bf:itemOf present there is always be a schema:bookFormat schema:EBook statement is created regardless of the actual format of the instance.
This was the input: http://data.hnm.hu/id/colls/lib/bib/MNMKVT17960#Instance
And this is the result:
<http://data.hnm.hu/id/colls/lib/bib/MNMKVT17960#Instance>
        a                     schema:Book , schema:CreativeWork , bf:Instance ;
        schema:bookFormat     schema:EBook ;
        schema:datePublished  "cop. 1996" , "1996" ;
        schema:description    "Rajz. Nagy Katalin, Pintér Katalin, Vári Ágnes" , "ill., főként színes" , "Bibliogr.: p. 71." ;
        schema:exampleOfWork  <http://data.hnm.hu/id/colls/lib/bib/MNMKVT17960#Work> ;
        schema:isbn           "9638155574 (kötött)" ;
        schema:name           "Die Heilige Krone von Ungarn : Könige und Krönungen" ;
        schema:numberOfPages  "71 p." ;
        schema:publication    [ a                 schema:PublicationEvent ;
                                schema:location   [ a            schema:Place ;
                                                    schema:name  "Veszprém"
                                                  ] ;
                                schema:location   [ a            schema:Place ;
                                                    schema:name  "Budapest"
                                                  ] ;
                                schema:organizer  _:b2 , _:b3 ;
                                schema:startDate  "cop. 1996"
                              ] ;
        schema:publisher      _:b3 , _:b2 .

_:b6    a            schema:Organization ;
        schema:name  "Kossuth" .

[input-rdfxml.txt](https://github.com/NatLibFi/bib-rdf-pipeline/files/2608446/input-rdfxml.txt)

**Comment by osma** [comment]
Thanks for the report @HorvathAdam ! Could you also attach the original MARC record (in any format) so that it could be used for the unit tests?

**Comment by HorvathAdam** [comment]
Here it is in many formats.


[input-marc-mrc.txt](https://github.com/NatLibFi/bib-rdf-pipeline/files/2644158/input-marc-mrc.txt)
[input-marc-mrk.txt](https://github.com/NatLibFi/bib-rdf-pipeline/files/2644159/input-marc-mrk.txt)
[input-marc-xml.txt](https://github.com/NatLibFi/bib-rdf-pipeline/files/2644160/input-marc-xml.txt)

**Comment by osma** [comment]
Finally got around to fixing this. The problem was that the 850 field (holding institution) caused a bf:itemOf relationship and this got turned into format EBook. 850 is not used in Fennica data so the only itemOf relationships there are for EBooks.
